from __future__ import annotations

import shutil
import csv
import re
import sys
import subprocess
import contextlib
import io
import os
import string
import random
import functools
import types
import asyncio
import inspect
import json
import openai
import toml
import time
import yaml
import hashlib
import copy
import traceback
import keyboard
import threading
import pandas as pd
import datetime
import logging
import dataclasses
import pyttsx3
import enum
import typing
import ipaddress
import typing_extensions
import typing_inspection
import tkinter as tk
import warnings
import collections
import importlib
import pathlib
import argparse
import ctypes
import colorama
import speedtest
import speedtest_cli
import rich
import rich
import rich.abc
import rich.align
import rich.ansi
import rich.bar
import rich.box
import rich.cells
import rich.color
import rich.color_triplet
import rich.columns
import rich.console
import rich.constrain
import rich.containers
import rich.default_styles
import rich.emoji
# import rich.emoji_data
import rich.errors
import rich.file_proxy
import rich.filesize
import rich.highlighter
import rich.json
import rich.jupyter
import rich.layout
import rich.live
import rich.live_render
import rich.logging
import rich.markdown
import rich.measure
import rich.padding
import rich.pager
import rich.pager
import rich.palette
import rich.panel
import rich.pretty
import rich.progress
import rich.progress_bar
import rich.prompt
import rich.region
import rich.repr
import rich.rule
import rich.scope
import rich.screen
import rich.segment
# import rich.sizing
import rich.spinner
import rich.status
import rich.style
import rich.styled
import rich.syntax
import rich.table
import rich.terminal_theme
import rich.text
import rich.theme
import rich.traceback
import rich.tree
# import rich.win32_console
from types import NotImplementedType
from colorama import Fore, Back, Style
from collections import defaultdict
from tkinter import ttk, font
from enum import Enum, auto, IntEnum
from dataclasses import dataclass
from weakref import WeakValueDictionary
from functools import wraps
from fpdf import FPDF
from configparser import ConfigParser
from dataclasses import dataclass, field, fields, is_dataclass
from typing import (
    Any, 
    Callable, 
    Literal, 
    Type, 
    Set, 
    Tuple, 
    List, 
    Dict, 
    Optional, 
    ClassVar, 
    Iterable, 
    Union, 
    TypeVar, 
    Generic, 
    get_origin, 
    get_args,
    Protocol,
    runtime_checkable,
    overload,
    cast,
    final,
    NewType,
    Iterator,
    NoReturn,
    TypedDict,
    NotRequired,
    Unpack,
    TypeAlias,
    Self,
    ParamSpec,
    LiteralString
)
from typing_extensions import disjoint_base
from abc import ABC, abstractmethod
from pathlib import Path
from datetime import datetime
from copy import deepcopy

try:
    from watchdog.observers import Observer
    from watchdog.events import FileSystemEventHandler
except ImportError:
    ...

T = TypeVar("T")
F = TypeVar("F", bound=Callable[..., Any])
U = TypeVar("U")
E = TypeVar("E", bound=BaseException)
_T = TypeVar("T")
_F = TypeVar("F", bound=Callable[..., Any])
P = ParamSpec("P")
R = TypeVar("R")


_MetaType: TypeAlias = int | float | str | None

mixed = NewType("mixed", typing.Any)
number = NewType("number", int)
byte = NewType("byte", bytes)
array = NewType("array", dict)
sequence = NewType("sequence", str)

def do_not_return(obj): ...
def noop_decor_callback(func: F) -> F: ...
def inline(func: F) -> F: ...
@final
def export(identifier: str, value: Any, *, ephemeral: Type[Any]): ...
def critical(func: F) -> F: ... 
def pure(func: F) -> F: ...
def memoize(func: F) -> F: ...

class CMeta:
    __slots__: tuple[str]
    def __init__(self, version=(1, 0, 0), build="") -> None: ...
    @property
    def version(self) -> tuple: ...
    @property
    def build(self) -> str: ...
    @property
    def version_str(self) -> str: ...
    @property
    def full_version(self) -> str: ...
    def __repr__(self) ->str: ...
    def __str__(self) -> str: ...

CMETA: CMeta

class CNarator:
    def __init__(
        self, 
        ini_data: Optional[Dict[str, Dict[str, Any]]] = None, 
        voice: Optional[str] = None, 
        rate: int = 150, 
        volume: float = 1.0
    ) -> None: ...
    def register_callback(self, callback: Callable[[str, Dict[str, Any]], None]) -> None: ...
    def _speak(self, message: str, context: Optional[Dict[str, Any]] = None) -> None: ...
    def narrate_set(self, section: str, key: str, value: Any) -> None: ...
    def narrate_delete(self, section: str, key: str) -> None: ...
    def narrate_read(self, section: Optional[str] = None, key: Optional[str] = None) -> Any | Dict[str, Any] | Dict[str, Dict[str, Any]] | None: ...
    def narrate_file_load(self, filepath: Union[str, Path]) -> list[str] | None: ...
    def narrate_file_save(self, filepath: Union[str, Path]) -> None: ...

class CObjectMeta(type):
    def __new__(mcls, name, bases, ns) -> Self: ...

class CObject(ABC):
    __abstract__: bool
    TYPE_NAME: ClassVar[str]
    __validators__: ClassVar[List[Callable]]
    __processors__: ClassVar[List[Callable]]
    __traits__: ClassVar[set]
    raw: str
    lineno: Optional[int]
    def __init__(self, raw: str, *, lineno: Optional[int] = None) -> None: ...
    def _run_validators(self) -> None: ...
    def process(self, value: Any, stage: str) -> Any: ...
    @classmethod
    def traits(cls) -> Iterable[str]: ...
    @classmethod
    def describe(cls) -> Dict[str, Any]: ...
    @abstractmethod
    def serialize(self) -> str: ...

class CType(Enum):
    REGION: int
    KEY: int
    VALUE: int
    COMMENT: int
    EMPTY: int
    NOT_IMPLEMENTED: int
    UNKNOWN: int

@dataclass(slots=True)
class CNode:
    type: CType
    raw: str
    lineno: Optional[int]

class INIOTypeRegistry:
    _registry: ClassVar[WeakValueDictionary[str, Type["CObject"]]]
    @classmethod
    def register(cls, type_name: str, typ: Type["CObject"]) -> None: ...
    @classmethod
    def resolve(cls, type_name: str) -> Type["CObject"]: ...
    @classmethod
    def all_types(cls) -> Dict[str, Type["CObject"]]: ...

def trait(name: str) -> Callable[[type[Any]], type[Any]]: ...
def validator(func: Callable[["CObject"], None]) ->  Callable[..., Any]: ...
def processor(stage: str) -> Callable[[Callable[[Any, Any], Any]], Callable[[Any, Any], Any]]: ...

class INIRegion(CObject):
    __traits__: list
    TYPE_NAME: str
    name: str
    def __init__(self, name: str, raw: str, *, lineno=None) -> None: ...
    def _validate_name(self) -> None: ...
    def serialize(self) -> str: ...

class INIComment(CObject):
    __traits__: list
    TYPE_NAME: str
    text: str
    marker: str
    def __init__(self, text: str, raw: str, marker=";", *, lineno=None) -> None: ...
    def serialize(self) -> str: ...

class INIKeyValue(CObject):
    __traits__: list
    TYPE_NAME: str
    key: str
    value: Any
    separator: str
    def __init__(self, key: str, value: Any, raw: str, sep="=", *, lineno=None) -> None: ...
    def _validate_key(self) -> None: ...
    def _stringify_value(self, value) -> str: ...
    def serialize(self) -> str: ...

class INIONotImplemented(CObject):
    __traits__: list
    TYPE_NAME: str
    reason: str
    def __init__(self, raw: str, reason="unsupported", *, lineno=None) -> None: ...
    def serialize(self) -> str: ...

class Node:
    def __init__(self, key: str, value: Any, section: str = "DEFAULT") -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, new_value) -> None: ...
    def attach_observer(self, fn: Callable[['Node'], None]) -> None: ...
    def _notify(self) -> None: ...
    def __repr__(self) -> str: ...

class VirtualNode(Node):
    def __init__(self, key: str, compute: Callable[[], Any], section: str = "DEFAULT") -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, _) -> None: ...

class ConfigGraph:
    def __init__(self) -> None: ...
    def add_node(self, node: Node) -> None: ...
    def get(self, section: str, key: str) -> Optional[Node]: ...
    def transaction(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def serialize(self) -> str: ...

def copy_node(node: Node) -> Node: ...

class ExportObserver:
    def __init__(self) -> None: ...
    def attach(self, callback: Callable[[], None]) -> None: ...
    def notify(self) -> None: ...

class INIExporter:
    def __init__(self, source: Union[str, ConfigParser, List[Any]]): ...
    def _from_nodes(self, nodes: List[Any]) -> ConfigParser: ...
    def to_excel(
        self,
        path: str,
        sheet_by_section: bool = True,
        highlight_sections: Optional[List[str]] = None,
    ): ...
    def to_pdf(
        self,
        path: str,
        include_timestamp: bool = True,
        table_style: Optional[Dict[str, Any]] = None,
    ): ...
    def attach_export_observer(self, callback: Callable[[], None]): ...
    def transaction(self): ...
    def commit(self): ...
    def rollback(self): ...

class IniValidator:
    def __init__(self, schema: Dict[str, Dict[str, Dict[str, Any]]]): ...
    def validate(self, ini_data: Dict[str, Dict[str, Any]]) -> None: ...

class IniWatcher:
    def __init__(self, filepath: Union[str, Path], callback: Callable[[str], None]): ...
    def _compute_hash(self) -> str: ...
    def _on_modified(self, event): ...
    def start(self): ...
    def stop(self): ...

class IniSerializer:
    def __init__(self, ini_data: Dict[str, Dict[str, Any]]) -> None: ...
    def to_json(self, pretty: bool = True) -> str: ...
    def to_yaml(self) -> str: ...
    def to_toml(self) -> str: ...
    def to_ini_string(self, align: bool = True) -> str: ...

class IniDiff:
    def __init__(self, base_data: Dict[str, Dict[str, Any]], new_data: Dict[str, Dict[str, Any]]) -> None: ...
    def diff(self) -> Dict[str, Dict[str, Tuple[Any, Any]]]: ...
    def patch(self, target: Dict[str, Dict[str, Any]]) -> Dict[str, Dict[str, Any]]: ...

class IniPlaceholderEngine:
    def __init__(self, ini_data: Dict[str, Dict[str, Any]], env: Optional[Dict[str, str]] = None) -> None: ...
    def _resolve_env(self, var_name: str) -> str: ...
    def _resolve_key(self, key_path: str) -> str: ...
    def resolve_value(self, value: str) -> str: ...
    def resolve_all(self) -> Dict[str, Dict[str, Any]]: ...

class IniAuditLogger:
    def __init__(self, ini_data: Dict[str, Dict[str, Any]], log_file: Optional[str] = None) -> None: ...
    def set(self, section: str, key: str, value: Any) -> None: ...
    def delete(self, section: str, key: str) -> None: ...
    def get(self, section: str, key: str) -> Any: ...

class INIO:
    def __init__(
       self,
       path: str,
       *,
       mode: Literal["r", "w", "a"] = ...,
       encoding: str = "utf-8",
       errors: Literal["strict", "ignore", "replace"] = ...,
       r: bool = ...,
       k: bool = ...,
       keys: dict[str, str] | None = ...,
       restrict: bool | None = ...,
       raises: Type[Exception] | None = ...,
       fallback: Any | Callable | None = ...,
       aliases: dict[Any, dict[Any, Any]] | list[Any] | None = ...,
       components: dict[str, list[str]] | None = ...,
    ) -> None: ...
    @property
    def meta(self): ...
    def _resolve_placeholder_value(
        self, 
        value: str, 
        region: str, 
        visited: Set[Tuple[str, str]] = ...
    ) -> str: ...
    def _rebuild_memory(self) -> None: ...
    def _write_file(self) -> None: ...
    def _resolve_value(self, value: str, current_region: str, visited: set = ...) -> str: ...
    def _update_memory_and_file(self, new_full_file: list[str]) -> None: ...
    def _prune_duplicates_in_region_dev_copy(self, region: str) -> list[str]: ...
    def _prune_empty_keys_dev_copy(self, region: str) -> list[str]: ...
    def _resolve_dev_copy(self, region: str) -> dict[str, str]: ...
    def _prune_empty_regions_dev_copy(self) -> list[str]: ...
    def _resolve_placeholders(
        self, 
        value: str, 
        region: str, 
        visited: Set[Tuple[str, str]] | None = ...
    ) -> str: ...
    def resolve(self, region: str) -> dict[str, str]: ...
    def load(self) -> bool: ...
    def reload(self) -> None: ...
    def empty(
        self,
        t: Literal["@var", "@region", "@key"],
        var: str | None = ...,
        region: str | None = ...,
        key: str | None = ...
    ) -> bool: ...
    def getregions(self) -> list[str]: ...
    def getkeys(self) -> dict[str, str]: ...
    def rexist(self, region: str) -> bool: ...
    def kexist(self, region: str, key: str) -> bool: ...
    def normalize(self, region: str) -> list[str]: ...
    def populate(self, region: str, value: str) -> list[str]: ...
    def mutate(self, region: str, key: str, value: str) -> bool: ...
    def assign(self, region: str, key: str | dict[str, str], value: str | None = None) -> bool: ...
    def register(self, region: str) -> None: ...
    def prune_empty_keys(self, region: str) -> list[str]: ...
    def prune_empty_regions(self) -> list[str]: ...
    def get(self, region: str, key: str) -> str | None: ...
    def gather(self, region: str) -> dict[str, str] | None: ...
    def get_duplicates(self, region: str) -> dict[str, str]: ...
    def delete(self, region: str, key: str) -> bool: ...
    def rremove(self, region: str) -> bool: ...
    def prune_duplicate_keys(self, region: str) -> list[str]: ...
    def prune_duplicates(self) -> list[str]: ...
    def prune_duplicate_regions(self) -> list[str]: ...
    def plain_sanitize(
        self, 
        remove_comments: bool = ..., 
        preserve_inline: bool = ...
    ) -> dict[str, list[str]]: ...
    def sanitize_strict(
        self,
        remove_comments: bool = ...,
        preserve_inline: bool = ...,
        dry_run: bool = ...
    ) -> dict[str, list[str]]: ...
    def get_region(self, region: str) -> Dict[str, str]: ...
    def get_duplicates(self, region: str) -> Dict[str, str]: ...
    def resolve_region(self, target: str, copy: bool = ...) -> Dict[str, str]: ...
    def sanitize(
        self,
        remove_comments: bool = ...,
        remove_duplicate_keys: bool = ...,
        remove_duplicate_regions: bool = ...,
        space_between_regions: bool = ...,
        dry_run: bool = ...,
        resolve_placeholders: bool = ...
    ) -> Dict[str, List[str]]: ...
    def spacefy_full(self) -> None: ...
    def spacefy(self) -> None: ...
    def length(self) -> int: ...
    def size(self) -> int: ...
    def clear(self) -> None: ...
    def get_duplicate_keys(self, region: str) -> list[str]: ...
    def copyto(self, region: str, to: str) -> None: ...
    def leftout(self) -> list[str]: ...
    def copy_key(self, region: str, key: str, to: str) -> tuple[str, str]: ...
    def put(self, content: dict[str, str]) -> bool: ...
    def inp(self, content: list[str]) -> bool: ...
    def backup(self, to: str) -> bool: ...
    def template(self, region: str, content: dict[str, str]) -> dict: ...
    def execute(self, tpl: dict) -> bool: ...
    def flush(self) -> bool: ...
    def destroy(self) -> bool: ...
    def rename_region(self, old: str, new: str) -> bool: ...
    def rename_key(self, region: str, old_key: str, new_key: str) -> bool: ...
    def batch(self, *steps, strict: bool = ..., debug: bool = ...) -> list: ...
    def snapshot(self) -> dict: ...
    def restore(self, snapshot: dict) -> None: ...
    def diff(self) -> list[str]: ...
    def pattern_search(self, pattern: str) -> dict[str, list[str]]: ...
    def validate_struct(self) -> list[str]: ...
    def merge(self, other: "INIO", overwrite: bool = ...) -> None: ...
    def export(self) -> dict[str, dict[str, str]]: ...
    def clone(self, path: str) -> bool: ...
    def trace(self) -> str: ...
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    def file_mode(self): ...
    def is_readonly(self) -> bool: ...
    def findall(self, key: str) -> list[str]: ...
    def file_stats(self) -> dict[str, int]: ...
    def strip_comments(self) -> None: ...
    def swap_regions(self, a: str, b: str) -> bool: ...
    def bulk_assign(self, region: str, mapping: dict[str, str]) -> int: ...
    def dry_run(self, fn, *args, **kwargs): ...
    def require(self, region: str, keys: list[str]) -> None: ...
    def hook(self, event: str, fn) -> None: ...
    def _emit(self, event: str) -> None: ...
    def stdbatch(self, *ops, **opts) -> Any: ...
    class Region:
        def __init__(self, ini: "INIO", name: str, base: str | None = ...) -> None: ...
        def extend(self) -> None: ...
        def resolve(self) -> None: ...
        def resolve_functions(self) -> None: ...
    class Expo:
        class INIOError(Exception):
            def __init__(self, message: str = ..., *, context: dict | None = ...) -> None: ...
            def __str__(self) -> str: ...
            def __repr__(self) -> str: ...
            def __eq__(self, other) -> bool: ...
            def __hash__(self) -> int: ...
            def __reduce__(self): ...
        class FileError(INIOError):
            def __init__(self, path: str, message: str) -> None: ...
        class FileNotFound(FileError, FileNotFoundError):
            def __init__(self, path: str) -> None: ...
        class FilePermission(FileError, PermissionError):
            def __init__(self, path: str) -> None: ...
        class FileWriteError(FileError, IOError):
            def __init__(self, path: str) -> None: ...
        class RegionError(INIOError):
            def __init__(self, region: str, message: str) -> None: ...
        class InvalidRegion(RegionError, KeyError):
            def __init__(self, region: str) -> None: ...
        class DuplicateRegion(RegionError, ValueError):
            def __init__(self, region: str) -> None: ...
        class DataError(Exception):
            def __init__(self, *args) -> None: ...
        class ReadError(Exception):
            def __init__(self, *args) -> None: ...
        class TunnelError(Exception):
            def __init__(self, *args) -> None: ...
        class ConnectionException(RuntimeError):
            def __init__(self, *args) -> None: ...
        class KeyErrorEx(INIOError):
            def __init__(self, region: str, key: str, message: str) -> None: ...
        class InvalidKey(KeyErrorEx, KeyError):
            def __init__(self, region: str, key: str) -> None: ...
        class DuplicateKey(KeyErrorEx, ValueError):
            def __init__(self, region: str, key: str) -> None: ...
        class PlaceholderError(INIOError):
            def __init__(self, placeholder: str, message: str) -> None: ...
        class UnresolvedPlaceholder(PlaceholderError):
            def __init__(self, placeholder: str) -> None: ...
        class CircularPlaceholder(PlaceholderError, RuntimeError):
            def __init__(self, chain: list[str]) -> None: ...
        class ValidationError(INIOError, ValueError):
            def __init__(self, message: str, *, field: str | None = None) -> None: ...
    
    class EBX(Exception):
        def __init__(self, *args) -> None: ...
        def __str__(self) -> str: ...
        def __repr__(self) -> str: ...
        def __eq__(self, other: Any) -> NotImplementedType | bool: ...
        def __ne__(self, other: Any) -> NotImplementedType | bool: ...
        def __hash__(self) -> int: ...
        def __getattribute__(self, name: Any) -> Any: ...
        def __setattr__(self, name: Any, value: Any) -> None: ...
        def __delattr__(self, name: Any) -> None: ...
        def with_traceback(self, tb: Any) -> Self: ...
        @property
        def __cause__(self) -> Any: ...
        @__cause__.setter
        def __cause__(self, value: Any) -> None: ...
        @property
        def __context__(self) -> Any: ...
        @__context__.setter
        def __context__(self, value) -> None: ...
        @property
        def __suppress_context__(self) -> Any: ...
        @__suppress_context__.setter
        def __suppress_context__(self, value) -> None: ...
        def __reduce__(self) -> tuple[type[Self], tuple[Any, ...]]: ...
        def __reduce_ex__(self, protocol: Any) -> tuple[type[Self], tuple[Any, ...]]: ...
        def __dir__(self) -> Iterable[str]: ...
        def __bool__(self) -> Literal[True]: ...
    class STDOP:
        def __init__(self, ini: "INIO") -> None: ...
        def if_not_loaded(self, msg: str = "INI not loaded") -> None: ...
        def if_dirty(self, msg: str = "INI memory differs from disk") -> None: ...
        def if_empty(self, msg: str = "INI loaded but empty") -> None: ...
        def if_missing_region(self, region: str) -> None: ...
        def if_missing_key(self, region: str, key: str) -> None: ...
        def lock(self, reason: str) -> None: ...
        def unlock(self) -> None: ...
        def panic(self, reason: str) -> None: ...
        def exit(self, code: int = 1) -> None: ...
        def assert_writable(self) -> None: ...
        def status(self) -> dict[str, str | bool]: ...
        def debug(self) -> str: ...
    class Pretty:
        RESET: str
        BLACK: str
        RED: str
        GREEN: str
        YELLOW: str
        BLUE: str
        MAGENTA: str
        CYAN: str
        WHITE: str
        BOLD: str
        DIM: str
        UNDERLINE: str
        BLINK: str
        REVERSE: str
        OK: str
        SUCCESS: str
        WARN: str
        FAIL: str
        ERR: str
        INFO: str
        DEBUG: str
        @classmethod
        def paint(cls, text: str, *styles: str) -> str: ...
        @staticmethod
        def line(char: str = "─", width: int = 60) -> str: ...
        @staticmethod
        def title(text: str, char: str = "=") -> str: ...
        @classmethod
        def block(cls, title: str, content: str, color: str = "") -> str: ...
        @classmethod
        def ok(cls, text: str) -> str: ...
        @classmethod
        def success(cls, text: str) -> str: ...
        @classmethod
        def warn(cls, text: str) -> str: ...
        @classmethod
        def fail(cls, text: str) -> str: ...
        @classmethod
        def error(cls, text: str) -> str: ...
        @classmethod
        def info(cls, text: str) -> str: ...
        @classmethod
        def debug(cls, text: str) -> str: ...
        @classmethod
        def std_ok(cls, text: str) -> str: ...
        @classmethod
        def std_success(cls, text: str) -> str: ...
        @classmethod
        def std_warn(cls, text: str) -> str: ...
        @classmethod
        def std_fail(cls, text: str) -> str: ...
        @classmethod
        def std_error(cls, text: str) -> str: ...
        @classmethod
        def std_info(cls, text: str) -> str: ...
        @classmethod
        def std_debug(cls, text: str) -> str: ...
        @staticmethod
        def dump(obj, indent: int = 2) -> str: ...
        @staticmethod
        def dump_table(
            data: list[dict[str, str]], 
            headers: list[str] | None = None, 
            indent: int = 2
        ) -> str: ...
        @staticmethod
        def print(text: str, flush: bool = True) -> None: ...
        @classmethod
        def banner(cls, text: str, width: int = 60, char: str = "*") -> str: ...
        @classmethod
        def key_value(
            cls, 
            key: str, 
            value: str, 
            key_color: str = "", 
            value_color: str = ""
        ) -> str: ...
    class Conn:
        def __init__(self, ini_instance: "INIO") -> None: ...
        def file(self) -> bool: ...
        def loaded(self) -> bool: ...
        def ok(self) -> bool: ...
        def data(self) -> bool: ...
        def regions(self) -> bool: ...
        def keys(self) -> bool: ...
        def empty(self) -> bool: ...
        def dirty(self) -> bool: ...
        def unparsed_regions(self) -> list[str]: ...
        def summary(self) -> dict[str, bool | list[str]]: ...
        def debug(self) -> str: ...
        def assert_loaded(self) -> None: ...
    
    class Filesystem:
        @staticmethod
        def create(
            path: str, 
            overwrite: bool = False, 
            ensure_dir: bool = True
        ) -> bool: ...
        @staticmethod
        def read_raw(path: str) -> str | None: ...
        @staticmethod
        def read_structured(path: str) -> dict[str, dict[str, str]] | None: ...
        @staticmethod
        def append(path: str, content: dict[str, dict[str, str]]) -> bool: ...
        @staticmethod
        def overwrite(path: str, content: dict[str, dict[str, str]]) -> bool: ...
        @staticmethod
        def flush(path: str) -> bool: ...
        @staticmethod
        def destroy(path: str) -> bool: ...
        @staticmethod
        def backup(path: str, to: str) -> bool: ...

    class Wrap:
        @staticmethod
        def _capture_state(ini: "INIO") -> dict: ...
        @staticmethod
        def _restore_state(ini: "INIO", state: dict) -> None: ...
        @classmethod
        def requires_loaded(
            cls: type[Self]
        ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
        @classmethod
        def requires_file(
            cls: type[Self]
        ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
        @classmethod
        def read_only(
            cls: type[Self]
        ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
        @classmethod
        def dry_run(
            cls: type[Self]
        ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
        @classmethod
        def atomic(
            cls: type[Self]
        ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
        @classmethod
        def with_backup(
            cls: type[Self], 
            *, 
            suffix: str
        ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
        @classmethod
        def warn_if_dirty(
            cls: type[Self]
        ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
        @classmethod
        def validate_regions(
            cls: type[Self]
        ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
        @classmethod
        def batch(cls, *functions) -> Any | None | ("INIO"): ...
        @staticmethod
        def ini_feature(name: str) -> Callable[[type[T]], type[T]]: ...

    class Awaitable:
        def __init__(self, parent: INIO) -> None: ...
        async def _call(self, fn: Any, *args: Any, **kwargs: Any) -> Any: ...
        async def load(self) -> Any: ...
        async def save(self) -> Any: ...
        async def assign(self, region: str, key: str, value: Any) -> Any: ...
        async def delete(self, region: str, key: str) -> Any: ...
        async def delete_region(self, region: str) -> Any: ...
        async def populate(self, region: str, value: Any = ...) -> Any: ...
        async def normalize(self, region: str) -> Any: ...
        async def resolve(self, region: str) -> Any: ...
        async def get(self, region: str, key: str) -> Any: ...
        async def regions(self) -> list[str]: ...
        async def keys(self) -> list[str]: ...
        async def raw_lines(self) -> list[str]: ...
        async def full_file(self) -> list[str]: ...
        @staticmethod
        async def destroy(path: str) -> bool: ...

class INIODEBUG(INIO):
    def __init__(self, *args, debug=..., strict=..., **kwargs) -> None: ...
    def debug_call(self, name: str | None = ...) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def debug_time(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def debug_exceptions(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def snapshot_state(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def _capture_state(self) -> dict: ...
    def _compare_state(self, before: dict, after: dict, context: str) -> None: ...
    def _push_trace(self, name: str) -> None: ...
    def _pop_trace(self) -> None: ...
    def load(self, *args: Any, **kwargs: Any) -> Any: ...
    def batch(self, *steps: Any, strict: bool = ..., debug: bool = ...) -> Any: ...
    def _update_memory_and_file(self, new_full_file: list[str]) -> None: ...
    def dump_state(self) -> None: ...
    def trace_tree(self) -> LiteralString: ...
    def assert_region(self, region: str) -> None: ...
    def assert_key(self, region: str, key: str) -> None: ...
    def load(self, *args, **kwargs) -> Any: ...
    def _update_memory_and_file(self, new_full_file: list[str]) -> None: ...
    def batch(self, *steps, strict: bool = True, debug: bool = False) -> list: ...
    def trace(self) -> str: ...
    def dump_state(self) -> None: ...
    def safe_execute(self, *steps, **kwargs) -> list | None: ...

class INIODESCRIBE:
    def __init__(self, path: str) -> None: ...
    def section(self, name: str) -> Self: ...
    def key(self, name: str) -> Self: ...
    def as_str(self) -> Self: ...
    def as_int(self) -> Self: ...
    def as_float(self) -> Self: ...
    def as_bool(self) -> Self: ...
    def as_path(self) -> Self: ...
    def list_of(self, subtype: Any) -> Self: ...
    def map_of(self, key_type: Any, value_type: Any) -> Self: ...
    def _set_type(self, typ: Any) -> Self: ...
    def default(self, value: Any) -> Self: ...
    def required(self) -> Self: ...
    def enum(self, *values: Any) -> Self: ...
    def doc(self, text: str) -> Self: ...
    def alias(self, name: str) -> Self: ...
    def deprecated(self, reason: str | None = ...) -> Self: ...
    def env(self, var_name: str) -> Self: ...
    def cli(self, flag: str) -> Self: ...
    def transform(self, fn: Any) -> Self: ...
    def on_change(self, fn: Any) -> Self: ...
    def freeze(self) -> Self: ...
    def clone(self) -> Self: ...
    def describe(self) -> str: ...
    def build(self) -> INIO: ...
    def _assert_key(self) -> None: ...
    def _assert_not_frozen(self) -> None: ...

class INIOTyped(Generic[T]):
    def __init__(self, value: T) -> None: ...
    def get(self) -> T: ...
    def __repr__(self) -> str: ...

class INIOHINTS:
    def __init__(self, data: dict[str, Any]) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __repr__(self) -> str: ...

class INIODOCS:
    def __init__(self, description: dict[str, dict[str, Any]]) -> None: ...
    def to_markdown(self) -> str: ...
    def to_text(self) -> str: ...

def describe(path: str) -> Callable[[Any], Any]: ...

class INIOMODEL:
    def __init__(
        self,
        model: type[Any],
        *,
        section: str | None = ...,
        strict: bool = ...,
        frozen: bool = ...,
    ) -> None: ...

    def build(self, data: dict[str, Any]) -> Any: ...
    def diff(self, a: Any, b: Any) -> dict[str, tuple[Any, Any]]: ...
    def _build_dataclass(self, cls: type[Any], values: dict[str, Any]) -> Any: ...
    def _coerce_value(self, typ: type[Any], value: Any) -> Any: ...
    def _field_key(self, f: dataclasses.Field | Any) -> str: ...
    def _freeze(self, obj: Any) -> None: ...

class INIOApi(INIO):
    def __init__(self, path: str) -> None: ...
    def get_section(self, section: str) -> dict: ...
    def set_section(self, section: str, values: dict) -> None: ...
    def delete_section(self, section: str) -> None: ...
    def get(self, section: str, key: str, default=...) -> str | None: ...
    def set(self, section: str, key: str, value: Any) -> None: ...
    def delete(self, section: str, key: str) -> None: ...
    def register_hook(
        self, 
        hook: Callable[['INIOApi', str, dict], None], 
        when=...
    ) -> None: ...
    def _run_hooks(self, section: Any, changes: Any, when: Any) -> None: ...
    def decorate(self, section: str, key: str) -> Callable[[F], F]: ...
    def _apply_decorators(self, section: str, changes: dict, when: str) -> None: ...
    def _snapshot(self) -> None: ...
    def rollback(self, version: int) -> None: ...
    def history(self) -> list: ...
    def search_keys(self, pattern: str) -> list: ...
    def filter_by_value(self, predicate: Callable[[Any], bool]) -> list: ...
    def describe(self) -> str: ...
    def export_dict(self) -> dict: ...
    def merge_dict(self, other: dict) -> None: ...
    def to_json(self) -> str: ...
    def from_json(self, json_str: str) -> None: ...
    @staticmethod
    def validate_type(expected_type: type[Any]) -> Callable[
        [Callable[[Any, Any, Any, Any], Any]],
        Callable[[Any, Any, Any, Any], Any]
    ]: ...
    @staticmethod
    def log_changes(func: Callable[..., Any]) -> Callable[..., Any]: ...
    @staticmethod
    def cache_last_value(func: Callable[..., Any]) -> Callable[..., Any]: ...
    @staticmethod
    def require_keys(
        *required_keys: str
    ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    @staticmethod
    def trigger_event(
        event_name: str
    ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

class INIOAI:
    def __init__(
        self, 
        api: "INIOApi", 
        model: str = ...
    ) -> None: ...
    def snapshot(self) -> None: ...
    def undo(self) -> None: ...
    def edit(self, instruction: str) -> Dict[str, Any]: ...
    def _query_ai(self, prompt: str) -> str: ...
    def apply_type_validation(self, section: str, key: str, expected_type: type) -> None: ...
    def apply_logging(self, section: str, key: str) -> None: ...
    def apply_event(self, section: str, key: str, event_name: str) -> None: ...
    def apply_cache(self, section: str, key: str) -> None: ...
    def apply_required_keys(self, section: str, *keys: str) -> None: ...
    def to_json(self) -> str: ...
    def from_json(self, json_str: str) -> None: ...
    def describe(self) -> str: ...

@runtime_checkable
class _CallableLike(Protocol):
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class INIODecorators(Generic[T]):
    __slots__: tuple[str, ...]
    def __init__(self, target: T | None = None, *args: Any, **kwargs: Any) -> None: ...
    @overload
    def __call__(self, target: F) -> F: ...
    @overload
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __get__(self, instance: Any, owner: Any) -> Any: ...
    def __class_getitem__(cls: type[Self], item: Any) -> type[Self]: ...
    @property
    def __wrapped__(self) -> Any: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> Any: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> bool: ...
    def signature(self) -> inspect.Signature | None: ...
    def source(self) -> str | None: ...
    def noop_decorator(func: F) -> F: ...
    def identity_decorator(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
    def destroy(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
    def get(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
    def set(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
    def default(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
    def override(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
    def die(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
    def do_not_return(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
    def strict(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
    def metadata_passthrough(**meta: Any) -> Callable[[F], F]: ...
    def overview(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
    def placeholder(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
    def deport(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
    class Void(Generic[T]):
        def __init__(self, target: T | None = ..., *args: Any, **kwargs: Any) -> None: ...
        @overload
        def __call__(self, target: F) -> F: ...
        @overload
        def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
        def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
        def __get__(self, instance: Any, owner: Any) -> Any: ...
        @property
        def __wrapped__(self) -> Any: ...
        def __repr__(self) -> str: ...
        def __getattr__(self, name: str) -> Any: ...
        def __enter__(self) -> Self: ...
        def __exit__(
            self, 
            exc_type: type[BaseException] | None, 
            exc: BaseException | None, 
            tb: Any
        ) -> bool: ...
        def do_not_return(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...

    class Mark(Generic[T]):
        def __init__(self, target: T | None = ..., *args: Any, **kwargs: Any) -> None: ...
        @overload
        def __call__(self, target: F) -> F: ...
        @overload
        def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
        def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
        def __get__(self, instance: Any, owner: Any) -> Any: ...
        @property
        def __wrapped__(self) -> Any: ...
        def __repr__(self) -> str: ...
        def __getattr__(self, name: str) -> Any: ...
        def __enter__(self) -> Self: ...
        def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any) -> bool: ...
        def this(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
        def argument(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...

    class Flag(Generic[T]):
        def __init__(self, target: T | None = ..., *args: Any, **kwargs: Any) -> None: ...
        def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
        def __get__(self, instance: Any, owner: Any) -> Any: ...
        def __repr__(self) -> str: ...
        def __getattr__(self, name: str) -> Any: ...
        def __enter__(self) -> Self: ...
        def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any) -> bool: ...
        @property
        def __wrapped__(self) -> Any: ...
        def placeholder(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
        def encode(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...

    class Final(Generic[T]):
        def __init__(self, target: T | None = ..., *args: Any, **kwargs: Any) -> None: ...
        def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
        def __get__(self, instance: Any, owner: Any) -> Any: ...
        def __repr__(self) -> str: ...
        def __getattr__(self, name: str) -> Any: ...
        def __enter__(self) -> Self: ...
        def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any) -> bool: ...
        @property
        def __wrapped__(self) -> Any: ...
        def check(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...

    class Protected(Generic[T]):
        def __init__(self, target: T | None = ..., *args: Any, **kwargs: Any) -> None: ...
        def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
        def __get__(self, instance: Any, owner: Any) -> Any: ...
        def __repr__(self) -> str: ...
        def __getattr__(self, name: str) -> Any: ...
        def __enter__(self) -> Self: ...
        def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any) -> bool: ...
        @property
        def __wrapped__(self) -> Any: ...
        def set(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
        def this(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...

    class Override(Generic[T]):
        def __init__(self, target: T | None = ..., *args: Any, **kwargs: Any) -> None: ...
        def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
        def __get__(self, instance: Any, owner: Any) -> Any: ...
        def __repr__(self) -> str: ...
        def __getattr__(self, name: str) -> Any: ...
        def __enter__(self) -> Self: ...
        def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any) -> bool: ...
        @property
        def __wrapped__(self) -> Any: ...
        def setter(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
        def attr(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...
        def label(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...

class namespace:
    Whatever: typing.Any
    Object: type[object]
    Integer: type[int]
    Float: type[float]
    Boolean: type[bool]
    String: type[str]
    Complex: type[complex]
    Tuple: type[tuple]
    List: type[list]
    Dict: type[dict]
    Set: type[set]
    FrozenSet: type[frozenset]
    Range: type[range]
    Bytes: type[bytes]
    ByteArray: type[bytearray]
    MemoryView: type[memoryview]
    NoneType: type[None]
    NaN: type[None]
    EllipsisType: type[ellipsis]
    NotImplementedType: type[Any]
    Function: type[types.FunctionType]
    BuiltinFunction: type[types.BuiltinFunctionType]
    INIObjectMethod: type[INIO]
    Mixed: typing.Any
    mixed: typing.Any
    sequence: str
    Sequence: str
    array: dict
    Array: dict
    @classmethod
    def __class_getitem__(cls, item: type[T]) -> type[T]: ...
    def strict(*dargs: Any, **dkwargs: Any) -> Callable[[F], F]: ...

class INIOExecute:
    def __init__(self, filepath: str) -> None: ...
    def _load_file(self) -> None: ...
    def _parse_line(self, raw: str, lineno: int) -> "INIKeyValue" | None: ...
    def batch(self, cmd: str) -> Any | None: ...
    def get(self, key: str) -> Any | None: ...
    def set(self, key: str, value: str) -> str: ...
    def delete(self, key: str) -> str: ...
    def list(self, section: str) -> dict[str, Any]: ...
    def show(self) -> LiteralString: ...
    def save(self, out: Optional[str] = ...) -> str: ...
    def transaction(self: Self) -> Literal['transaction started']: ...
    def rollback(self: Self) -> Literal['rolled back']: ...
    def commit(self: Self) -> Literal['committed']: ...

class INIOActivity:
    def __init__(self, ini_object: Dict[str, Dict[str, Any]]) -> None: ...
    def set(self, section: str, key: str, value: Any) -> None: ...
    def delete(self, section: str, key: str) -> None: ...
    def _insert_tree_items(self, tree: ttk.Treeview, parent: str, data: Dict[str, Any]) -> None: ...
    def show_tkinter_tree(
        self: Self,
        title: str = ...,
        width: int = ...,
        height: int = ...,
        font_name: str = ...,
        font_size: int = ...,
        section_color: str = ...,
        key_color: str = ...,
        background_color: str = ...,
        expand_all: bool = ...
    ) -> None: ...
    def export_to_dict(self: Self) -> Dict[str, Any]: ...
    def export_to_json(self: Self, indent: int = ...) -> str: ...
    def show_canvas_tree(self: Self, node_width=..., node_height=..., x_spacing=30, y_spacing=...) -> None: ...

class JSW:
    def __init__(self, file: str) -> None: ...
    def memset(self) -> dict: ...
    def reload_if_changed(self) -> bool: ...
    def save(self, atomic: bool = ...) -> None: ...
    def _validate_key(self, key: str) -> None: ...
    def resolve(self, path: str, default: Any = ...) -> Any: ...
    def exists(self, path: str) -> bool: ...
    def is_dict(self, path: str) -> bool: ...
    def is_list(self, path: str) -> bool: ...
    def is_primitive(self, path: str) -> bool: ...
    def get(self, path: str) -> Any: ...
    def gettp(self, path: str, t: type) -> Any: ...
    def getdeeptp(self, path: str, expected: Any) -> Any: ...
    def set(self, path: str, value: Any) -> None: ...
    def keys(self, path: str = ...) -> List[str]: ...
    def items(self, path: str = ...) -> List[tuple]: ...
    def values(self, path: str = ...) -> list: ...
    def diff(self) -> None: ...
    def dump(self) -> None: ...
    def templatelist(self, path: str, type_list: list) -> None: ...
    def executelist(self, path: str, values: list) -> None: ...
    def template(self, path: str, spec: Any) -> None: ...
    def execute(self, path: str, value: Any) -> None: ...
    def tpempty(self, path: str, t: Type) -> bool: ...
    def empty(
        self,
        path: str,
        types: Optional[Union[Type, Tuple[Type, ...]]] = ...,
        *,
        strict: bool = ...
    ) -> bool: ...
    def not_empty(
        self,
        path: str,
        types: Optional[Union[Type, Tuple[Type, ...]]] = ...,
        *,
        strict: bool = ...
    ) -> bool: ...
    def wildcard(self, path: str) -> list | Any: ...
    def remove(self, path: str) -> bool: ...
    def filldef(self, defaults: dict, base_path: str = ...) -> None: ...
    def merge(self, other: dict, base_path: str = ...) -> None: ...
    def snapshot(self) -> None: ...
    def undo(self) -> None: ...